#pragma config(I2C_Usage, I2C1, i2cSensors) 
#pragma config(Sensor, in1,    leftArmPot,     sensorPotentiometer) 
#pragma config(Sensor, dgtl1,  Jumper,         sensorDigitalIn) 
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign) 
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign) 
#pragma config(Motor,  port1,           rightIntake,   tmotorVex393, openLoop) 
#pragma config(Motor,  port2,           rightFrontDrive, tmotorVex393, openLoop, reversed) 
#pragma config(Motor,  port3,           rightBackDrive, tmotorVex393, openLoop, reversed, encoder, encoderPort, I2C_2, 1000) 
#pragma config(Motor,  port4,           rightTopArm,   tmotorVex393, openLoop) 
#pragma config(Motor,  port5,           rightBottomArm, tmotorVex393, openLoop) 
#pragma config(Motor,  port6,           leftTopArm,    tmotorVex393, openLoop, reversed) 
#pragma config(Motor,  port7,           leftBottomArm, tmotorVex393, openLoop, reversed) 
#pragma config(Motor,  port8,           leftFrontDrive, tmotorVex393, openLoop) 
#pragma config(Motor,  port9,           leftBackDrive, tmotorVex393, openLoop, encoder, encoderPort, I2C_1, 1000) 
#pragma config(Motor,  port10,          leftIntake,    tmotorVex393, openLoop, reversed) 
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*// 
  
#pragma platform(VEX) 
  
//Competition Control and Duration Settings 
#pragma competitionControl(Competition) 
#pragma autonomousDuration(60) 
#pragma userControlDuration(60) 
  
//Main competition background code...do not modify! 
#include "Vex_Competition_Includes.c" 
  
// These reference our own files 
#include "Utilities.c" 
#include "Constants.c" 
#include "Subsystem_Functions.c" 
#include "Autonomous_Modes.c" 
#include "Autonomous_Selection.c" 
  
///////////////////////////////////////////////////////////////////////////////////////// 
// 
//                          Pre-Autonomous Functions 
// 
// Actions that are performed before the match starts are coded here. 
// 
///////////////////////////////////////////////////////////////////////////////////////// 
  
void pre_auton() 
{ 
  // Set bStopTasksBetweenModes to false if you want to keep user created tasks running between 
  // Autonomous and Tele-Op modes. You will need to manage all user created tasks if set to false. 
  bStopTasksBetweenModes = true; 
  
    // All activities that occur before the competition starts 
    // Example: clearing encoders, setting servo positions, ... 
  
  initArmLimits();        // determine Dead or Alive robot and set arm limits accordingly 
  initAllPids();          // set all the PID constants 
  if (nLCDButtons != 0)   // if any LCD buttons are pressed during startup... 
    {selectAutonomous();} // ...allow the user to select which autonomous to run. 
} 
  
///////////////////////////////////////////////////////////////////////////////////////// 
// 
//                                 Autonomous Task 
// 
// This task is used to control the robot during the autonomous phase of competition. 
// 
///////////////////////////////////////////////////////////////////////////////////////// 
  
task autonomous() 
{ 
    runSelectedAutonomous(); // runs an autonomous routine based on the selection from the LCD 
                             // see "Autonomous_Modes.c" for the different routines 
} 
  
///////////////////////////////////////////////////////////////////////////////////////// 
// 
//                                 User Control Task 
// 
// This task is used to control the robot during the user control phase of competition. 
// 
///////////////////////////////////////////////////////////////////////////////////////// 
  
task usercontrol() 
{ 
    while (true)  // BLT (Big Loop Technology) 
    { 
      // This is the main execution loop for user control. Each time through the loop 
      // the program updates motor values based on feedback from the Joystick. 
  
      setDrive(); 
      setArm(); 
      setIntake(); 
      displayBatteryVoltage(); 
    } 
} 
